const iconData = {
  "Naturaleza": [
    { "char": "􁔑", "name": "naturaleza viaje acampar campamento camp campañas" },
    { "char": "􁋩", "name": "naturaleza viaje tienda acampar campamento" },
    { "char": "􁗞", "name": "naturaleza paisaje montañas horiente" },
    { "char": "􁝰", "name": "naturaleza nature arbol tree bio bosque campo parque paseo"},
    { "char": "􀙖", "name": "naturaleza hogar paraguas sombrilla lluvia preparar" },
    { "char": "􁖏", "name": "naturaleza comida carrot verdura zanahoria vegetal vegetable nature" },
    { "char": "􁋻", "name": "naturaleza sombrilla playa salida paraguas lluvia sol relajacion" },
    { "char": "􁋺", "name": "naturaleza aire libre" },
    { "char": "􁂙", "name": "naturaleza plantas leaves hojas maceta" },
    { "char": "􁂂", "name": "naturaleza plantas flores jardin flowers" },
    { "char": "􀥳", "name": "naturaleza hojas de arbol leaves ecology plantas leaf" },
    { "char": "􀠒", "name": "naturaleza agua tomar water drink drops" },
    { "char": "􀙭", "name": "naturaleza fuego fire racha lumbre" },
  { "char": "􀇛", "name": "" },
  { "char": "􀬮", "name": "" },
    { "char": "􀆺", "name": "naturaleza tiempo moon cycle dormir sleep noche night luna" },
    { "char": "􀇁", "name": "naturaleza luna sparkles brillito brillos noche dormir cielo" },
    { "char": "􀆮", "name": "naturaleza tiempo sol sun brillo brightness protector dia day sky cielo" },
    { "char": "􀆲", "name": "naturaleza tiempo amanecer puesta de sol" },
    { "char": "􀆴", "name": "naturaleza tiempo atardecer puesta de sol" },
    { "char": "􀇣", "name": "naturaleza nubes clouds sky cielo nublado" },
    { "char": "􀓑", "name": "animales fauna tortuga animal lento" },
    { "char": "􀓏", "name": "animales fauna conejo bunny liebre saltar" },
    { "char": "􀌛", "name": "animales fauna hormiga insecto" },
  { "char": "􁗜", "name": "" },
    { "char": "􁗠", "name": "animales fauna ave pajaro paloma libre volar" },
    { "char": "􂁿", "name": "animales fauna gato cat misifus" },
    { "char": "􂀇", "name": "animales fauna perro cachorro doggy paseo" },
    { "char": "􁖑", "name": "animales fauna pez fish nadar atun comida" },
    { "char": "􀯕", "name": "animales fauna insecto catarina ladybug mariquita" },
    { "char": "􀾟", "name": "animales fauna paw patita pata perro gato huellas" },
    { "char": "􀆿", "name": "tecnologia ai inteligencia artificial estrellas brillos brillitos sparkles" },
    { "char": "􀫸", "name": "tecnologia sparkles ai inteligencia artificial" },
  ],
  "Hogar y electrónicos": [
    { "char": "􁐟", "name": "electrodomesticos hogar refrigerador nevera heladera" },
    { "char": "􀐛", "name": "hogar oficina caja paquete box entrega" },
    { "char": "􁓃", "name": "limpieza hogar bañar bañarme bañarse ducha regadera" },
    { "char": "􁐫", "name": "limpieza hogar quehacer fregadero lavar llave grifo" },
    { "char": "􁐳", "name": "hogar muebles sofa sillon hueva descanso" },
    { "char": "􁐧", "name": "hogar electrodomesticos cocina" },
    { "char": "􁐿", "name": "limpieza hogar retrete inodoro escuzado baño caca popo" },
    { "char": "􀈒", "name": "limpieza hogar trash bin basura papelera" },
    { "char": "􁐡", "name": "limpieza hogar quehacer lavanderia laundry lavar lavadora ropa" },
    { "char": "􁐥", "name": "hogar electrodomesticos horno estufa cocinar" },
    { "char": "􀎡", "name": "hogar seguridad lock candado seguro" },
    { "char": "􁌝", "name": "hogar tecnologia foco lampara luz led" },
    { "char": "􀞄", "name": "hogar tecnologia slash tachado foco sin luz" },
    { "char": "􀟖", "name": "hogar seguridad key llaves llavero" },
    { "char": "􀠖", "name": "hogar gancho ropa guardar" },
    { "char": "􀑊", "name": "hogar regalo obsequio gift gratitud caja" },
    { "char": "􁎹", "name": "hogar electrodomesticos ventilador luz viento aire refrescar" },
    { "char": "􁐵", "name": "hogar muebles sofa sillon recreativo comoda relajar" },
    { "char": "􁖋", "name": "hogar limpieza laundry cesto campo picnic" },
    { "char": "􁐯", "name": "hogar quehacer ordenar mueble ropa ropero closet" },
    { "char": "􀙪", "name": "hogar descanso bed dormir sleep cama dormitorio" },
    { "char": "􀎟", "name": "hogar casa hogar house cabaña" }
  ],
  "Oficina y Educacion": [
    { "char": "􀎛", "name": "oficina print printer archivos tecnología papeles imprimir impresora papel" },
    { "char": "􀺑", "name": "keyboard, teclado, oficina, tecnología" },
    { "char": "􀤐", "name": "oficina trabajo papeles contrato negocio" },
    { "char": "􀈎", "name": "oficina redes editar escribir publicar post" },
    { "char": "􀋢", "name": "oficina etiqueta tag" },
    { "char": "􀉀", "name": "oficina archivos papeles documento imprimir hoja file pdf" },
    { "char": "􀥅", "name": "oficina news noticias periodico paper" },
    { "char": "􀫔", "name": "educacion escuela birrete" },
    { "char": "􀖆", "name": "educacion lectura leer anteojos lentes gafas" },
    { "char": "􀈖", "name": "oficina files papeles documentos archivos folder carpeta workspace" },
    { "char": "􁰎", "name": "educacion experimento ciencia quimica" },
    { "char": "􁙢", "name": "oficina tecnologia subir archivo actualizar documento backup" },
    { "char": "􁂥", "name": "oficina analiticas matematicas tracking estadisticas grafica tarea seguimiento tracker" },
    { "char": "􀫖", "name": "educacion test texto libro book escuela aprender" },
    { "char": "􁻧", "name": "oficina pendientes calendario tarea evento check" },
    { "char": "􀉉", "name": "oficina calendar caledario planear planeacion agenda" },
    { "char": "􀉛", "name": "educacion lectura libro leer book reading" },
    { "char": "􀤟", "name": "educacion lectura libro book diario journal" },
  { "char": "􀬚", "name": "" },
  { "char": "􁔗", "name": "" },
  ],
  "Entretenimiento y juego": [
    { "char": "􁐈", "name": "entretenimiento cine pelicula palomitas" },
    { "char": "􀥮", "name": "juego entretenimiento rompecabezas extension" },
    { "char": "􀲭", "name": "juego hogar teddy teddybear osito oso peluche" },
    { "char": "􀺨", "name": "entretenimiento chiste gracioso teatro caras burla" },
    { "char": "􀪄", "name": "entretenimiento boleto ticket" },
    { "char": "􀈠", "name": "juego avion papel manualidad" },
    { "char": "􁶺", "name": "entretenimiento pelicula cinematografia" },
    { "char": "􀑈", "name": "entretenimiento escuchar musica audifonos" },
    { "char": "􀛹", "name": "juego tecnologia juegos jugar consola xbox ps videojuegos game" },
    { "char": "􁖪", "name": "entretenimiento birthday cumpleaños fiesta pastel torta" },
    { "char": "􀙌", "name": "entretenimiento feliz happy face emoji mood" },
  ],
  "Salud y cuidado": [
    { "char": "􁌋", "name": "deportes lagartijas entrenamiento yoga ejercicio crunch" },
    { "char": "􁌓", "name": "deportes estiramiento entrenamiento gym ejercicio" },
    { "char": "􁐃", "name": "deportes pesas mancuernas repeticiones entrenamiento gym" },
    { "char": "􁖍", "name": "deportes ejercicio workout entrenar entrenamiento pesas gym mancuernas" },
    { "char": "􀝾", "name": "salud doctor chequeo ritmo cardiaco hospital" },
    { "char": "􁻈", "name": "salud accesorios anteojos lentes gafas vista ver" },
    { "char": "􁚮", "name": "salud medicina medicamento pastilla capsula pildora" },
    { "char": "􀦉", "name": "salud limpieza peinar peine pelo cabello estetica cepillo cepillar" },
    { "char": "􂃈", "name": "salud mente cerebro cabeza pensamiento" },
    { "char": "􀲯", "name": "limpieza salud lavar manos wash hands sparkles" },
    { "char": "􀦛", "name": "salud pulmones respirar respiracion lungs" },
    { "char": "􀦪", "name": "salud lips boca dientes lavar exfoliacion labios" },
    { "char": "􀠒", "name": "salud naturaleza agua tomar water drink drop" },
    { "char": "􁹡", "name": "" }
  ],
  "Herramientas y arte": [
    { "char": "􀤉", "name": "herramientas tools destornillador reparar" },
    { "char": "􀎖", "name": "herramientas tools perico llave" },
    { "char": "􀎒", "name": "herramientas arte pintar pintura brocha personalizar brush" },
    { "char": "􀣷", "name": "herramientas arte brush pincel pintar pintura" },
    { "char": "􀝦", "name": "" },
    { "char": "􀙅", "name": "herramientas tools martillo reparar" }
  ],
  "Alimentos y bebidas": [
    { "char": "􀻑", "name": "comida bebida rapida compra" },
    { "char": "􁎥", "name": "comida copa beber wine vino lujo" },
    { "char": "􁞵", "name": "comida taza cup vaso cafe" },
    { "char": "􁐆", "name": "comida hogar huevo sarten desayuno morning oven pan" },
    { "char": "􀸙", "name": "comida taza de cafe cup te coffee" },
    { "char": "􂊭", "name": "comida cafe te caliente coffe tea cup" }
  ],
  "Transporte y viajes": [
    { "char": "􀶊", "name": "viaje maleta equipaje documentos" },
    { "char": "􀡥", "name": "" },
    { "char": "􀝉", "name": "" },
    { "char": "􁖹", "name": "" },
    { "char": "􀙋", "name": "viaje mapa location ubicacion ubicar maps" },
    { "char": "􀙙", "name": "transporte carro conducir carretera coche automovil" },
    { "char": "􀑓", "name": "transporte airplane avion aeropuerto viaje" },
    { "char": "􁝍", "name": "transporte stop alto signal señal" }
  ],
  "Personas y actividades": [
  { "char": "􁌐", "name": "" },
  { "char": "􁔴", "name": "salud meditacion chi relajacion meditate maditation meditar" },
  { "char": "􁒐", "name": "" },
  { "char": "􁒑", "name": "" },
  { "char": "􁔚", "name": "" },
  { "char": "􀝻", "name": "" },
  { "char": "􁔛", "name": "" },
  { "char": "􁔜", "name": "" },
  { "char": "􁔝", "name": "" },
  { "char": "􁔞", "name": "" },
  { "char": "􁔟", "name": "" },
  { "char": "􁔠", "name": "" },
  { "char": "􁌒", "name": "" },
  { "char": "􁔣", "name": "" },
  { "char": "􂞣", "name": "" },
  { "char": "􁔧", "name": "" },
  { "char": "􁕑", "name": "" },
  { "char": "􁔩", "name": "" },
  { "char": "􁔪", "name": "" },
  { "char": "􁔬", "name": "" },
  { "char": "􁌎", "name": "" },
  { "char": "􁌌", "name": "" },
  { "char": "􁔭", "name": "" },
  { "char": "􁔮", "name": "" },
  { "char": "􂟇", "name": "" },
  { "char": "􂟀", "name": "" },
  { "char": "􁌋", "name": "" },
  { "char": "􁔰", "name": "" },
  { "char": "􁌉", "name": "" },
  { "char": "􂟄", "name": "" },
  { "char": "􁌓", "name": "" },
  { "char": "􁔸", "name": "" },
  { "char": "􁌆", "name": "" },
  { "char": "􁈑", "name": "" },
  { "char": "􀐳", "name": "" },
  { "char": "􁔽", "name": "" },
  { "char": "􁔤", "name": "" },
  { "char": "􁔾", "name": "" },
  { "char": "􁕂", "name": "" },
  { "char": "􁕃", "name": "" },
  { "char": "􁕄", "name": "" },
  { "char": "􁔨", "name": "" },
  { "char": "􁐃", "name": "" },
  { "char": "􁕅", "name": "" },
  { "char": "􀝢", "name": "" },
  { "char": "􁒌", "name": "" },
  ],
  "Comunicación": [
    { "char": "􀌥", "name": "comunicacion burbuja mensaje bubble chat whatsapp imessage" },
    { "char": "􀍇", "name": "comunicacion tecnologia phone telefono call llamada decline rechazar colgar" },
    { "char": "􀌿", "name": "comunicacion tecnologia call phone llamada telefono" },
    { "char": "􂤄", "name": "comunicacion manos hand saludo" },
  { "char": "􀕻", "name": "" },
  { "char": "􂛥", "name": "" },
  { "char": "􀌯", "name": "" },
  { "char": "􀘲", "name": "" },
  { "char": "􁃓", "name": "" },
  { "char": "􂃨", "name": "" },
  { "char": "􀌫", "name": "" },
  { "char": "􀌭", "name": "" },
  { "char": "􂄽", "name": "" },
  { "char": "􁗯", "name": "" },
  { "char": "􁂫", "name": "" },
  { "char": "􀌳", "name": "" },
  { "char": "􀮙", "name": "" },
  { "char": "􀍊", "name": "" },
  { "char": "􀙫", "name": "" }
  ],
  "Otro": [
    { "char": "􀌟", "name": " tecnologia camara fotografia tomar" },
    { "char": "􀡸", "name": "tecnología hogar enchufe cable conectar" },
    { "char": "􀪕", "name": "entretenimiento tecnología radio" },
    { "char": "􀜎", "name": "herramientas tecnologia varita magia ajustar reparar personalizar ai" },
    { "char": "􀬳", "name": "comunicacion megafono noticia avisar gritar" },
    { "char": "􀩯", "name": "tecnologia wifi modem internet" },
    { "char": "􀸸", "name": "tecnologia dispositivos devices airpods audifonos escuchar musica poner play" },
    { "char": "􀋞", "name": "tecnologia bell off disabeled campana notificaciones alertas phone disturb" },
    { "char": "􀋚", "name": "tecnologia bell on volume campana notificaciones alertas phone disturb" },
    { "char": "􀝗", "name": "tecnologia bell campana notificacion alerta phone" },
    { "char": "􀢋", "name": "tecnologia cargar bateria pila energia" },
    { "char": "􀟞", "name": "tecnologia dispositivos devices screentime tiempo en pantalla phone iphone celular telefono apps homescreen" },
    { "char": "􀙈", "name": "tecnologia wifi internet desconectar" },
    { "char": "􀙇", "name": "tecnologia wifi internet" },
    { "char": "􀊚", "name": "entretenimiento tecnologia video youtube" },
    { "char": "􀊄", "name": "entretenimiento tecnologia play reproducir video pelicula musica" },
    { "char": "􀌥", "name": "comunicacion burbuja mensaje bubble chat whatsapp imessage" },
    { "char": "􀊱", "name": "comunicacion microphone microfono voice record voz grabación" },
    { "char": "􀍇", "name": "comunicacion tecnologia phone telefono call llamada decline rechazar colgar" },
    { "char": "􀌿", "name": "comunicacion tecnologia call phone llamada telefono" },
    { "char": "􂤄", "name": "comunicacion manos hand saludo" },
    { "char": "􀉼", "name": "comunicacion no stop mano hand prohibido" },
    { "char": "􂤂", "name": "comunicacion hand mano saludo señal" },
    { "char": "􀖇", "name": "tiempo tecnologia temporizador reloj hora" },
    { "char": "􀐫", "name": "tiempo reloj clock" },
    { "char": "􀐮", "name": "tiempo tecnologia alarma despertador reloj" },
    { "char": "􁟣", "name": "" },
    { "char": "􀟛", "name": "" },
    { "char": "􀬂", "name": "" },
    { "char": "􁟠", "name": "" },
    { "char": "􁊲", "name": "" },
    { "char": "􁊵", "name": "" },
    { "char": "􀢺", "name": "" },
    { "char": "􀏮", "name": "" },
    { "char": "􀯮", "name": "" },
    { "char": "􀲲", "name": "" },
  { "char": "􀇰", "name": "" },
  { "char": "􁔗", "name": "" },
  { "char": "􁓦", "name": "" },
  { "char": "􀬚", "name": "" },
  { "char": "􁗌", "name": "" },
  { "char": "􀢓", "name": "" },
  { "char": "􀢔", "name": "" },
  { "char": "􀎔", "name": "" },
  { "char": "􀰍", "name": "" },
  { "char": "􂚧", "name": "" },
  { "char": "􁓸", "name": "" },
  { "char": "􂂇", "name": "" },
  { "char": "􁔏", "name": "" },
  { "char": "􂒳", "name": "" },
  { "char": "􀰐", "name": "" },
  { "char": "􀐬", "name": "" },
  { "char": "􀠎", "name": "" },
  { "char": "􁐽", "name": "" },
  { "char": "􂂆", "name": "" },
  { "char": "􁑠", "name": "" },
  { "char": "􁖫", "name": "" },
  { "char": "􀡶", "name": "" },
  { "char": "􀍤", "name": "" },
  { "char": "􀅈", "name": "" },
  { "char": "􁗊", "name": "" },
  { "char": "􀣝", "name": "" },
  { "char": "􀐯", "name": "" },
  { "char": "􀄩", "name": "" },
  { "char": "􀐱", "name": "" },
  { "char": "􀯵", "name": "" },
  { "char": "􁖋", "name": "" },
  { "char": "􀒽", "name": "" },
  { "char": "􀱅", "name": "" },
  { "char": "􁝁", "name": "" },
  { "char": "􁼀", "name": "" },
  { "char": "􀎘", "name": "" },
  { "char": "􀍖", "name": "" },
  { "char": "􀈮", "name": "" },
  { "char": "􁐵", "name": "" },
  { "char": "􀦇", "name": "" },
  { "char": "􁹟", "name": "" },
  { "char": "􂙢", "name": "" },
  { "char": "􀁹", "name": "" },
  { "char": "􀁍", "name": "" },
  { "char": "􀊄", "name": "" },
  { "char": "􀊵", "name": "" },
  { "char": "􀍚", "name": "" },
  { "char": "􀊚", "name": "" },
  { "char": "􀵟", "name": "" },
  { "char": "􀥵", "name": "" },
  { "char": "􀈶", "name": "" },
  { "char": "􀟖", "name": "" },
  { "char": "􁠲", "name": "" },
  { "char": "􂜱", "name": "" },
  { "char": "􃀨", "name": "" },
  { "char": "􁕝", "name": "" },
  { "char": "􀋒", "name": "" },
  { "char": "􁼌", "name": "" },
  { "char": "􁣉", "name": "" },
  { "char": "􀍪", "name": "" },
  { "char": "􁚮", "name": "" },
  { "char": "􀙋", "name": "" },
  { "char": "􀠲", "name": "" },
  { "char": "􀎫", "name": "" },
  { "char": "􃔀", "name": "" },
  { "char": "􀠸", "name": "" },
  { "char": "􁏝", "name": "" },
  { "char": "􁏜", "name": "" },
  { "char": "􁏩", "name": "" },
  { "char": "􁏨", "name": "" },
  { "char": "􀄉", "name": "" },
  { "char": "􀓈", "name": "" },
  { "char": "􀓉", "name": "" },
  { "char": "􀰑", "name": "" },
  { "char": "􀰒", "name": "" },
  { "char": "􀛩", "name": "" },
  { "char": "􀈎", "name": "" },
  { "char": "􀛨", "name": "" },
  { "char": "􀰕", "name": "" },
  { "char": "􀢋", "name": "" },
  { "char": "􀓔", "name": "" },
  { "char": "􀍰", "name": "" },
  { "char": "􁋻", "name": "" },
  { "char": "􀺭", "name": "" },
  { "char": "􀁺", "name": "" },
  { "char": "􀁻", "name": "" },
  { "char": "􀄋", "name": "" },
  { "char": "􀄫", "name": "" },
  { "char": "􁈐", "name": "" },
  { "char": "􀁼", "name": "" },
  { "char": "􂚨", "name": "" },
  { "char": "􀁽", "name": "" },
  { "char": "􀄍", "name": "" },
  { "char": "􂓳", "name": "" },
  { "char": "􁌉", "name": "" },
  { "char": "􂣽", "name": "" },
  { "char": "􂣾", "name": "" },
  { "char": "􀙟", "name": "" },
  { "char": "􀍊", "name": "" },
  { "char": "􀙫", "name": "" },
  { "char": "􀄬", "name": "" },
  { "char": "􀁶", "name": "" },
  { "char": "􂚪", "name": "" },
  { "char": "􀁷", "name": "" },
  { "char": "􀶷", "name": "" },
  { "char": "􁜔", "name": "" },
  { "char": "􀛹", "name": "" },
  { "char": "􂎺", "name": "" },
  { "char": "􂂪", "name": "" },
  { "char": "􁗈", "name": "" },
  { "char": "􀝐", "name": "" },
  { "char": "􀝑", "name": "" },
  { "char": "􁜧", "name": "" },
  { "char": "􁜫", "name": "" }
  ]
};
